namespace DAL.Vulcan.Mongo.DocClass.Notifications
{
    public enum NotificationObjectType
    {
        None,
        Quote,
        Task,
        Event,
        Note,
        Admin,
        Manager,
        Supervisor,
        SalesPerson,
        Contact,
        Document,
        Meeting,
        Phonecall,
        Email,
        Customer,
        Vendor,
        Employee,
        Company,
        CompanyGroup,
        Team,
        Goal,
        Reminder,
        Milestone,
        MessageGroup,
        Other,
        ScheduledEvent,
        Action,
        Fax,
        Prospect,
        Information
    }
}