//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using LinqConnect template.
// Code is generated on: 3/22/2018 7:34:54 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using Devart.Data.Linq;
using Devart.Data.Linq.Mapping;
using System.Data;
using System.ComponentModel;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Linq.Expressions;

namespace Vulcan.IMetal.Context.StockItems
{

    /// <summary>
    /// There are no comments for Vulcan.IMetal.Context.StockItems.StockAnalysisCode in the schema.
    /// </summary>
    [Table(Name = @"public.stock_analysis_codes")]
    public partial class StockAnalysisCode : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
        #pragma warning disable 0649

        private int _Id;

        private System.Nullable<int> _Version;

        private System.Nullable<System.DateTime> _Cdate;

        private System.Nullable<int> _CuserId;

        private System.Nullable<System.DateTime> _Mdate;

        private System.Nullable<int> _MuserId;

        private string _Status;

        private System.Nullable<int> _Type;

        private string _Code;

        private string _Description;
        #pragma warning restore 0649

        private EntitySet<ProductCategory> _ProductCategory_Analysis1Id;

        private EntitySet<ProductCategory> _ProductCategory_Analysis2Id;

        private EntitySet<Product> _Product_Analysis1Id;

        private EntitySet<Product> _Product_Analysis2Id;

        private EntitySet<Product> _Product_Analysis3Id;

        private EntitySet<Product> _Product_Analysis4Id;
    
        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        partial void OnVersionChanging(System.Nullable<int> value);
        partial void OnVersionChanged();
        partial void OnCdateChanging(System.Nullable<System.DateTime> value);
        partial void OnCdateChanged();
        partial void OnCuserIdChanging(System.Nullable<int> value);
        partial void OnCuserIdChanged();
        partial void OnMdateChanging(System.Nullable<System.DateTime> value);
        partial void OnMdateChanged();
        partial void OnMuserIdChanging(System.Nullable<int> value);
        partial void OnMuserIdChanged();
        partial void OnStatusChanging(string value);
        partial void OnStatusChanged();
        partial void OnTypeChanging(System.Nullable<int> value);
        partial void OnTypeChanged();
        partial void OnCodeChanging(string value);
        partial void OnCodeChanged();
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        #endregion

        public StockAnalysisCode()
        {
            this._ProductCategory_Analysis1Id = new EntitySet<ProductCategory>(new Action<ProductCategory>(this.attach_ProductCategory_Analysis1Id), new Action<ProductCategory>(this.detach_ProductCategory_Analysis1Id));
            this._ProductCategory_Analysis2Id = new EntitySet<ProductCategory>(new Action<ProductCategory>(this.attach_ProductCategory_Analysis2Id), new Action<ProductCategory>(this.detach_ProductCategory_Analysis2Id));
            this._Product_Analysis1Id = new EntitySet<Product>(new Action<Product>(this.attach_Product_Analysis1Id), new Action<Product>(this.detach_Product_Analysis1Id));
            this._Product_Analysis2Id = new EntitySet<Product>(new Action<Product>(this.attach_Product_Analysis2Id), new Action<Product>(this.detach_Product_Analysis2Id));
            this._Product_Analysis3Id = new EntitySet<Product>(new Action<Product>(this.attach_Product_Analysis3Id), new Action<Product>(this.detach_Product_Analysis3Id));
            this._Product_Analysis4Id = new EntitySet<Product>(new Action<Product>(this.attach_Product_Analysis4Id), new Action<Product>(this.detach_Product_Analysis4Id));
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for Id in the schema.
        /// </summary>
        [Column(Name = @"id", Storage = "_Id", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "SERIAL NOT NULL", IsDbGenerated = true, IsPrimaryKey = true)]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                if (this._Id != value)
                {
                    this.OnIdChanging(value);
                    this.SendPropertyChanging("Id");
                    this._Id = value;
                    this.SendPropertyChanged("Id");
                    this.OnIdChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Version in the schema.
        /// </summary>
        [Column(Name = @"""version""", Storage = "_Version", DbType = "INT4", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<int> Version
        {
            get
            {
                return this._Version;
            }
            set
            {
                if (this._Version != value)
                {
                    this.OnVersionChanging(value);
                    this.SendPropertyChanging("Version");
                    this._Version = value;
                    this.SendPropertyChanged("Version");
                    this.OnVersionChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Cdate in the schema.
        /// </summary>
        [Column(Name = @"cdate", Storage = "_Cdate", DbType = "TIMESTAMPTZ", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTime> Cdate
        {
            get
            {
                return this._Cdate;
            }
            set
            {
                if (this._Cdate != value)
                {
                    this.OnCdateChanging(value);
                    this.SendPropertyChanging("Cdate");
                    this._Cdate = value;
                    this.SendPropertyChanged("Cdate");
                    this.OnCdateChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for CuserId in the schema.
        /// </summary>
        [Column(Name = @"cuser_id", Storage = "_CuserId", DbType = "INT4", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<int> CuserId
        {
            get
            {
                return this._CuserId;
            }
            set
            {
                if (this._CuserId != value)
                {
                    this.OnCuserIdChanging(value);
                    this.SendPropertyChanging("CuserId");
                    this._CuserId = value;
                    this.SendPropertyChanged("CuserId");
                    this.OnCuserIdChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Mdate in the schema.
        /// </summary>
        [Column(Name = @"mdate", Storage = "_Mdate", DbType = "TIMESTAMPTZ", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<System.DateTime> Mdate
        {
            get
            {
                return this._Mdate;
            }
            set
            {
                if (this._Mdate != value)
                {
                    this.OnMdateChanging(value);
                    this.SendPropertyChanging("Mdate");
                    this._Mdate = value;
                    this.SendPropertyChanged("Mdate");
                    this.OnMdateChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for MuserId in the schema.
        /// </summary>
        [Column(Name = @"muser_id", Storage = "_MuserId", DbType = "INT4", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<int> MuserId
        {
            get
            {
                return this._MuserId;
            }
            set
            {
                if (this._MuserId != value)
                {
                    this.OnMuserIdChanging(value);
                    this.SendPropertyChanging("MuserId");
                    this._MuserId = value;
                    this.SendPropertyChanged("MuserId");
                    this.OnMuserIdChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Status in the schema.
        /// </summary>
        [Column(Name = @"status", Storage = "_Status", DbType = "CHAR(1)", UpdateCheck = UpdateCheck.Never)]
        public string Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                if (this._Status != value)
                {
                    this.OnStatusChanging(value);
                    this.SendPropertyChanging("Status");
                    this._Status = value;
                    this.SendPropertyChanged("Status");
                    this.OnStatusChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Type in the schema.
        /// </summary>
        [Column(Name = @"""type""", Storage = "_Type", DbType = "INT4", UpdateCheck = UpdateCheck.Never)]
        public System.Nullable<int> Type
        {
            get
            {
                return this._Type;
            }
            set
            {
                if (this._Type != value)
                {
                    this.OnTypeChanging(value);
                    this.SendPropertyChanging("Type");
                    this._Type = value;
                    this.SendPropertyChanged("Type");
                    this.OnTypeChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Code in the schema.
        /// </summary>
        [Column(Name = @"code", Storage = "_Code", DbType = "VARCHAR(3)", UpdateCheck = UpdateCheck.Never)]
        public string Code
        {
            get
            {
                return this._Code;
            }
            set
            {
                if (this._Code != value)
                {
                    this.OnCodeChanging(value);
                    this.SendPropertyChanging("Code");
                    this._Code = value;
                    this.SendPropertyChanged("Code");
                    this.OnCodeChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for Description in the schema.
        /// </summary>
        [Column(Name = @"description", Storage = "_Description", DbType = "VARCHAR(255)", UpdateCheck = UpdateCheck.Never)]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                if (this._Description != value)
                {
                    this.OnDescriptionChanging(value);
                    this.SendPropertyChanging("Description");
                    this._Description = value;
                    this.SendPropertyChanged("Description");
                    this.OnDescriptionChanged();
                }
            }
        }

    
        /// <summary>
        /// There are no comments for ProductCategory_Analysis1Id in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="StockAnalysisCode_ProductCategory", Storage="_ProductCategory_Analysis1Id", ThisKey="Id", OtherKey="Analysis1Id", DeleteRule="NO ACTION")]
        public EntitySet<ProductCategory> ProductCategory_Analysis1Id
        {
            get
            {
                return this._ProductCategory_Analysis1Id;
            }
            set
            {
                this._ProductCategory_Analysis1Id.Assign(value);
            }
        }

    
        /// <summary>
        /// There are no comments for ProductCategory_Analysis2Id in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="StockAnalysisCode_ProductCategory1", Storage="_ProductCategory_Analysis2Id", ThisKey="Id", OtherKey="Analysis2Id", DeleteRule="NO ACTION")]
        public EntitySet<ProductCategory> ProductCategory_Analysis2Id
        {
            get
            {
                return this._ProductCategory_Analysis2Id;
            }
            set
            {
                this._ProductCategory_Analysis2Id.Assign(value);
            }
        }

    
        /// <summary>
        /// There are no comments for Product_Analysis1Id in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="StockAnalysisCode_Product", Storage="_Product_Analysis1Id", ThisKey="Id", OtherKey="Analysis1Id", DeleteRule="NO ACTION")]
        public EntitySet<Product> Product_Analysis1Id
        {
            get
            {
                return this._Product_Analysis1Id;
            }
            set
            {
                this._Product_Analysis1Id.Assign(value);
            }
        }

    
        /// <summary>
        /// There are no comments for Product_Analysis2Id in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="StockAnalysisCode_Product1", Storage="_Product_Analysis2Id", ThisKey="Id", OtherKey="Analysis2Id", DeleteRule="NO ACTION")]
        public EntitySet<Product> Product_Analysis2Id
        {
            get
            {
                return this._Product_Analysis2Id;
            }
            set
            {
                this._Product_Analysis2Id.Assign(value);
            }
        }

    
        /// <summary>
        /// There are no comments for Product_Analysis3Id in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="StockAnalysisCode_Product2", Storage="_Product_Analysis3Id", ThisKey="Id", OtherKey="Analysis3Id", DeleteRule="NO ACTION")]
        public EntitySet<Product> Product_Analysis3Id
        {
            get
            {
                return this._Product_Analysis3Id;
            }
            set
            {
                this._Product_Analysis3Id.Assign(value);
            }
        }

    
        /// <summary>
        /// There are no comments for Product_Analysis4Id in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name="StockAnalysisCode_Product3", Storage="_Product_Analysis4Id", ThisKey="Id", OtherKey="Analysis4Id", DeleteRule="NO ACTION")]
        public EntitySet<Product> Product_Analysis4Id
        {
            get
            {
                return this._Product_Analysis4Id;
            }
            set
            {
                this._Product_Analysis4Id.Assign(value);
            }
        }
   
        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName) 
        {    
		        var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {    
		        var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }

        private void attach_ProductCategory_Analysis1Id(ProductCategory entity)
        {
            this.SendPropertyChanging("ProductCategory_Analysis1Id");
            entity.StockAnalysisCode_Analysis1Id = this;
        }
    
        private void detach_ProductCategory_Analysis1Id(ProductCategory entity)
        {
            this.SendPropertyChanging("ProductCategory_Analysis1Id");
            entity.StockAnalysisCode_Analysis1Id = null;
        }

        private void attach_ProductCategory_Analysis2Id(ProductCategory entity)
        {
            this.SendPropertyChanging("ProductCategory_Analysis2Id");
            entity.StockAnalysisCode_Analysis2Id = this;
        }
    
        private void detach_ProductCategory_Analysis2Id(ProductCategory entity)
        {
            this.SendPropertyChanging("ProductCategory_Analysis2Id");
            entity.StockAnalysisCode_Analysis2Id = null;
        }

        private void attach_Product_Analysis1Id(Product entity)
        {
            this.SendPropertyChanging("Product_Analysis1Id");
            entity.StockAnalysisCode_Analysis1Id = this;
        }
    
        private void detach_Product_Analysis1Id(Product entity)
        {
            this.SendPropertyChanging("Product_Analysis1Id");
            entity.StockAnalysisCode_Analysis1Id = null;
        }

        private void attach_Product_Analysis2Id(Product entity)
        {
            this.SendPropertyChanging("Product_Analysis2Id");
            entity.StockAnalysisCode_Analysis2Id = this;
        }
    
        private void detach_Product_Analysis2Id(Product entity)
        {
            this.SendPropertyChanging("Product_Analysis2Id");
            entity.StockAnalysisCode_Analysis2Id = null;
        }

        private void attach_Product_Analysis3Id(Product entity)
        {
            this.SendPropertyChanging("Product_Analysis3Id");
            entity.StockAnalysisCode_Analysis3Id = this;
        }
    
        private void detach_Product_Analysis3Id(Product entity)
        {
            this.SendPropertyChanging("Product_Analysis3Id");
            entity.StockAnalysisCode_Analysis3Id = null;
        }

        private void attach_Product_Analysis4Id(Product entity)
        {
            this.SendPropertyChanging("Product_Analysis4Id");
            entity.StockAnalysisCode_Analysis4Id = this;
        }
    
        private void detach_Product_Analysis4Id(Product entity)
        {
            this.SendPropertyChanging("Product_Analysis4Id");
            entity.StockAnalysisCode_Analysis4Id = null;
        }
    }

}
