using System;
using System.Collections.Generic;

namespace BI.DAL.DataWarehouse.Core.Models
{
    public partial class Arcus
    {
        public string Coid { get; set; }
        public string Idcust { get; set; }
        public decimal Audtdate { get; set; }
        public decimal Audttime { get; set; }
        public string Audtuser { get; set; }
        public string Audtorg { get; set; }
        public string Textsnam { get; set; }
        public string Idgrp { get; set; }
        public string Idnatacct { get; set; }
        public short Swactv { get; set; }
        public decimal Dateinac { get; set; }
        public decimal Datelastmn { get; set; }
        public short Swhold { get; set; }
        public decimal Datestart { get; set; }
        public string Idppnt { get; set; }
        public string Codedab { get; set; }
        public string Codedabrtg { get; set; }
        public decimal Datedab { get; set; }
        public string Namecust { get; set; }
        public string Textstre1 { get; set; }
        public string Textstre2 { get; set; }
        public string Textstre3 { get; set; }
        public string Textstre4 { get; set; }
        public string Namecity { get; set; }
        public string Codestte { get; set; }
        public string Codepstl { get; set; }
        public string Codectry { get; set; }
        public string Namectac { get; set; }
        public string Textphon1 { get; set; }
        public string Textphon2 { get; set; }
        public string Codeterr { get; set; }
        public string Idacctset { get; set; }
        public string Idautocash { get; set; }
        public string Idbillcycl { get; set; }
        public string Idsvcchrg { get; set; }
        public string Iddlnq { get; set; }
        public string Codecurn { get; set; }
        public short Swprtstmt { get; set; }
        public short Swprtdlnq { get; set; }
        public short Swbalfwd { get; set; }
        public string Codeterm { get; set; }
        public string Idratetype { get; set; }
        public string Codetaxgrp { get; set; }
        public string Idtaxregi1 { get; set; }
        public string Idtaxregi2 { get; set; }
        public string Idtaxregi3 { get; set; }
        public string Idtaxregi4 { get; set; }
        public string Idtaxregi5 { get; set; }
        public short Taxstts1 { get; set; }
        public short Taxstts2 { get; set; }
        public short Taxstts3 { get; set; }
        public short Taxstts4 { get; set; }
        public short Taxstts5 { get; set; }
        public decimal Amtcrlimt { get; set; }
        public decimal Amtbalduet { get; set; }
        public decimal Amtbaldueh { get; set; }
        public decimal Datelastst { get; set; }
        public decimal Amtlaststt { get; set; }
        public decimal Amtlaststh { get; set; }
        public decimal Dtbegbalfw { get; set; }
        public decimal Amtbalfwdt { get; set; }
        public decimal Amtbalfwdh { get; set; }
        public decimal Dtlastrval { get; set; }
        public decimal Amtballarv { get; set; }
        public decimal Cntopeninv { get; set; }
        public decimal Cntinvpaid { get; set; }
        public decimal Daystopay { get; set; }
        public decimal Dateinvchi { get; set; }
        public decimal Datebalhi { get; set; }
        public decimal Dateinvhil { get; set; }
        public decimal Datebalhil { get; set; }
        public decimal Datelastac { get; set; }
        public decimal Datelastiv { get; set; }
        public decimal Datelastcr { get; set; }
        public decimal Datelastdr { get; set; }
        public decimal Datelastpa { get; set; }
        public decimal Datelastdi { get; set; }
        public decimal Datelastad { get; set; }
        public decimal Datelastwr { get; set; }
        public decimal Datelastri { get; set; }
        public decimal Datelastin { get; set; }
        public decimal Datelastdq { get; set; }
        public string Idinvchi { get; set; }
        public string Idinvchily { get; set; }
        public decimal Amtinvhit { get; set; }
        public decimal Amtbalhit { get; set; }
        public decimal Amtinvhilt { get; set; }
        public decimal Amtbalhilt { get; set; }
        public decimal Amtlastivt { get; set; }
        public decimal Amtlastcrt { get; set; }
        public decimal Amtlastdrt { get; set; }
        public decimal Amtlastpyt { get; set; }
        public decimal Amtlastdit { get; set; }
        public decimal Amtlastadt { get; set; }
        public decimal Amtlastwrt { get; set; }
        public decimal Amtlastrit { get; set; }
        public decimal Amtlastint { get; set; }
        public decimal Amtinvhih { get; set; }
        public decimal Amtbalhih { get; set; }
        public decimal Amtinvhilh { get; set; }
        public decimal Amtbalhilh { get; set; }
        public decimal Amtlastivh { get; set; }
        public decimal Amtlastcrh { get; set; }
        public decimal Amtlastdrh { get; set; }
        public decimal Amtlastpyh { get; set; }
        public decimal Amtlastdih { get; set; }
        public decimal Amtlastadh { get; set; }
        public decimal Amtlastwrh { get; set; }
        public decimal Amtlastrih { get; set; }
        public decimal Amtlastinh { get; set; }
        public string Codeslsp1 { get; set; }
        public string Codeslsp2 { get; set; }
        public string Codeslsp3 { get; set; }
        public string Codeslsp4 { get; set; }
        public string Codeslsp5 { get; set; }
        public decimal Pctsasplt1 { get; set; }
        public decimal Pctsasplt2 { get; set; }
        public decimal Pctsasplt3 { get; set; }
        public decimal Pctsasplt4 { get; set; }
        public decimal Pctsasplt5 { get; set; }
        public string Priclist { get; set; }
        public short Custtype { get; set; }
        public decimal Amtpdue { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string Website { get; set; }
        public short Billmethod { get; set; }
        public string Paymcode { get; set; }
        public string Fob { get; set; }
        public string Shpviacode { get; set; }
        public string Shpviadesc { get; set; }
        public short Delmethod { get; set; }
        public string Primshipto { get; set; }
        public string Ctacphone { get; set; }
        public string Ctacfax { get; set; }
        public short Swpartship { get; set; }
        public short Swwebshop { get; set; }
        public decimal Rtgpercent { get; set; }
        public short Rtgdays { get; set; }
        public string Rtgterms { get; set; }
        public decimal Rtgamttc { get; set; }
        public decimal Rtgamthc { get; set; }
        public int Values { get; set; }
        public decimal Cntppdinvc { get; set; }
        public decimal Amtppdinvt { get; set; }
        public decimal Amtppdinvh { get; set; }
        public decimal Datelastrf { get; set; }
        public decimal Amtlastrft { get; set; }
        public decimal Amtlastrfh { get; set; }
        public string Codecheck { get; set; }
        public int Nextcuid { get; set; }
        public string Location { get; set; }
        public short Swchklimit { get; set; }
        public short Swchkover { get; set; }
        public short Overdays { get; set; }
        public decimal Overamt { get; set; }
        public short Swbackordr { get; set; }
        public short Swchkduppo { get; set; }
        public short? Category { get; set; }
        public string Brn { get; set; }
        public DateTime? EtlcreateDate { get; set; }
        public DateTime? EtlupdateDate { get; set; }
    }
}
