using System;
using System.Collections.Generic;

namespace BI.DAL.DataWarehouse.Core.Models
{
    public partial class Companies
    {
        public string Coid { get; set; }
        public int Id { get; set; }
        public int? Version { get; set; }
        public DateTime? Cdate { get; set; }
        public DateTime? Mdate { get; set; }
        public int? CuserId { get; set; }
        public int? MuserId { get; set; }
        public string Status { get; set; }
        public string Code { get; set; }
        public int? BranchId { get; set; }
        public int? PersonnelId { get; set; }
        public int? RelationshipId { get; set; }
        public int? StatusId { get; set; }
        public string Name { get; set; }
        public int? TerritoryId { get; set; }
        public string Telephone { get; set; }
        public string FastDial { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string WebAddress { get; set; }
        public int? ContactFrequency { get; set; }
        public bool? AcceptMail { get; set; }
        public bool? AcceptEmail { get; set; }
        public bool? AcceptFax { get; set; }
        public bool? AcceptCalls { get; set; }
        public bool? AcceptVisits { get; set; }
        public string GeneralNote { get; set; }
        public string ProductsNote { get; set; }
        public string CompetitionNote { get; set; }
        public string Categories { get; set; }
        public string AccessMethod { get; set; }
        public string Password { get; set; }
        public int? ParentCompanyId { get; set; }
        public DateTime? LastContactDate { get; set; }
        public string Idxfti { get; set; }
        public int? TermsId { get; set; }
        public string AccountsNote { get; set; }
        public int? AddressId { get; set; }
        public string ShortName { get; set; }
        public string Rank { get; set; }
        public int? CurrencyId { get; set; }
        public int? VatType1Id { get; set; }
        public int? VatType2Id { get; set; }
        public int? VatType3Id { get; set; }
        public int? VatType4Id { get; set; }
        public int? TypeId { get; set; }
        public int? SalesGroupId { get; set; }
        public int? CompanyTotalsId { get; set; }
        public int? CompanyCreditRulesId { get; set; }
        public bool? ShowPrices { get; set; }
        public bool? RequireSalesAcknowledgement { get; set; }
        public int? CertificationsId { get; set; }
        public int? InvoiceCompanyId { get; set; }
        public string PartnerCode { get; set; }
        public string CreditComments { get; set; }
        public string RegistrationNumber { get; set; }
        public bool? RequireProforma { get; set; }
        public int? CrmAccountId { get; set; }
        public bool? StatementRequired { get; set; }
        public DateTime? SynchronisationDate { get; set; }
        public DateTime? DateAppointed { get; set; }
        public int? DocumentDeliveryTypeId { get; set; }
        public int? DefaultContactId { get; set; }
        public int? DefaultBuyerId { get; set; }
        public string LedgerSegmentCode { get; set; }
        public int? SupplierRollingDays { get; set; }
        public int? DespatchNoteItemRuleId { get; set; }
        public string TaxGroup { get; set; }
        public string TaxAuthority1 { get; set; }
        public string TaxAuthority2 { get; set; }
        public string TaxAuthority3 { get; set; }
        public string TaxAuthority4 { get; set; }
        public string TaxAuthority5 { get; set; }
        public int? TaxClass1 { get; set; }
        public int? TaxClass2 { get; set; }
        public int? TaxClass3 { get; set; }
        public int? TaxClass4 { get; set; }
        public int? TaxClass5 { get; set; }
        public string TaxRegistration1 { get; set; }
        public string TaxRegistration2 { get; set; }
        public string TaxRegistration3 { get; set; }
        public string TaxRegistration4 { get; set; }
        public string TaxRegistration5 { get; set; }
        public bool? TaxExempt1 { get; set; }
        public bool? TaxExempt2 { get; set; }
        public bool? TaxExempt3 { get; set; }
        public bool? TaxExempt4 { get; set; }
        public bool? TaxExempt5 { get; set; }
        public string PopupNotes { get; set; }
        public int? AnalysisCode1Id { get; set; }
        public int? AnalysisCode2Id { get; set; }
        public int? AnalysisCode3Id { get; set; }
        public int? AnalysisCode4Id { get; set; }
        public decimal? PackingWeightPercentage { get; set; }
        public int? DefaultNominalCode { get; set; }
        public bool? InvoicePacking { get; set; }
        public string StockItemPrefix { get; set; }
        public int? DefaultOrderClassificationId { get; set; }
        public int? InvoiceBaseCurrencyFlag { get; set; }
        public bool? IntercompanyAccount { get; set; }
        public bool? PaymentHold { get; set; }
        public DateTime? EtlcreateDate { get; set; }
        public DateTime? EtlupdateDate { get; set; }
        public string TestCertificateSendMethod { get; set; }
        public string TestCertificateDestination { get; set; }
        public string TestCertificateHold { get; set; }
        public string InvoiceWeightRoundingMode { get; set; }
        public int? DefaultItemClass1 { get; set; }
        public int? DefaultItemClass2 { get; set; }
        public int? DefaultItemClass3 { get; set; }
        public int? DefaultItemClass4 { get; set; }
        public int? DefaultItemClass5 { get; set; }
        public int? AnalysisCode5Id { get; set; }
        public int? AnalysisCode6Id { get; set; }
        public int? OutworkBranchId { get; set; }
        public int? DefaultTransportTypeId { get; set; }
        public bool? CounterSalesDefault { get; set; }
        public int? FabricationPricingCategory { get; set; }
        public int? PriceBookLevel { get; set; }
        public bool ContractJobRequired { get; set; }
        public decimal? MinimumCashSalePaymentPercentage { get; set; }
        public string TransportComment { get; set; }
        public decimal? OutsideDiameter { get; set; }
        public decimal? OutsideDiameterMinimum { get; set; }
        public decimal? OutsideDiameterMaximum { get; set; }
        public decimal? PackHeight { get; set; }
        public decimal? PackHeightMinimum { get; set; }
        public decimal? PackHeightMaximum { get; set; }
        public decimal? PackWeight { get; set; }
        public decimal? PackWeightMinimum { get; set; }
        public decimal? PackWeightMaximum { get; set; }
        public decimal? InsideDiameter { get; set; }
        public decimal? InsideDiameterMinimum { get; set; }
        public decimal? InsideDiameterMaximum { get; set; }
        public int? PackCountMinimum { get; set; }
        public int? PackCountMaximum { get; set; }
    }
}
