using System;
using System.Collections.Generic;

namespace BI.DAL.DataWarehouse.Core.Models
{
    public partial class EomstockItems
    {
        public int? AuditArchiveId { get; set; }
        public DateTime? AccountingPeriod { get; set; }
        public DateTime? MotddateTime { get; set; }
        public string Coid { get; set; }
        public int Id { get; set; }
        public int Version { get; set; }
        public DateTime Cdate { get; set; }
        public int CuserId { get; set; }
        public DateTime Mdate { get; set; }
        public int MuserId { get; set; }
        public string Status { get; set; }
        public int? BranchId { get; set; }
        public string Number { get; set; }
        public int? WarehouseId { get; set; }
        public string TransientType { get; set; }
        public int? TransientId { get; set; }
        public string OtherNumber { get; set; }
        public string SupplierReference { get; set; }
        public int? ProductId { get; set; }
        public int? ProductSubGroupId { get; set; }
        public decimal? Dim1 { get; set; }
        public decimal? Dim1NegativeTolerance { get; set; }
        public decimal? Dim1PositiveTolerance { get; set; }
        public decimal? Dim2 { get; set; }
        public decimal? Dim2NegativeTolerance { get; set; }
        public decimal? Dim2PositiveTolerance { get; set; }
        public decimal? Dim3 { get; set; }
        public decimal? Dim3NegativeTolerance { get; set; }
        public decimal? Dim3PositiveTolerance { get; set; }
        public decimal? Dim4 { get; set; }
        public decimal? Dim4NegativeTolerance { get; set; }
        public decimal? Dim4PositiveTolerance { get; set; }
        public decimal? Dim5 { get; set; }
        public decimal? Dim5NegativeTolerance { get; set; }
        public decimal? Dim5PositiveTolerance { get; set; }
        public decimal? Density { get; set; }
        public int? StockCastId { get; set; }
        public int? SupplierId { get; set; }
        public int? PurchaseBranchId { get; set; }
        public int? PurchaseOrder { get; set; }
        public int? PurchaseOrderItem { get; set; }
        public string AdviceNoteReference { get; set; }
        public string TestCertReference { get; set; }
        public DateTime? ReceivedDate { get; set; }
        public DateTime? RejectedDate { get; set; }
        public int? RejectReasonId { get; set; }
        public string RejectDescription { get; set; }
        public int? CreationTransactionId { get; set; }
        public int? PhysicalPieces { get; set; }
        public decimal? PhysicalWeight { get; set; }
        public decimal? PhysicalQuantity { get; set; }
        public int? AllocatedPieces { get; set; }
        public decimal? AllocatedWeight { get; set; }
        public decimal? AllocatedQuantity { get; set; }
        public decimal? AdvisedQuantity { get; set; }
        public decimal? CalculatedQuantity { get; set; }
        public int? PackingTypeId { get; set; }
        public int? PiecesPerPack { get; set; }
        public string PackingReference { get; set; }
        public decimal? PackingWeight { get; set; }
        public decimal? MaterialCost { get; set; }
        public decimal? TransportCost { get; set; }
        public decimal? ProductionCost { get; set; }
        public decimal? MiscellaneousCost { get; set; }
        public decimal? SurchargeCost { get; set; }
        public decimal? MaterialValue { get; set; }
        public decimal? TransportValue { get; set; }
        public decimal? ProductionValue { get; set; }
        public decimal? MiscellaneousValue { get; set; }
        public decimal? SurchargeValue { get; set; }
        public decimal? OriginalMaterialCost { get; set; }
        public decimal? OriginalTransportCost { get; set; }
        public decimal? OriginalProductionCost { get; set; }
        public decimal? OriginalMiscellaneousCost { get; set; }
        public decimal? OriginalSurchargeCost { get; set; }
        public int? StockStatusId { get; set; }
        public int? CustomerId { get; set; }
        public int? PartSpecificationId { get; set; }
        public int? ProductionItem { get; set; }
        public string Location { get; set; }
        public string Notes { get; set; }
        public int? IdentifyingMarkId { get; set; }
        public string SpecificationValue1 { get; set; }
        public string SpecificationValue2 { get; set; }
        public string SpecificationValue3 { get; set; }
        public string SpecificationValue4 { get; set; }
        public string SpecificationValue5 { get; set; }
        public int? ParentId { get; set; }
        public int? OriginalParentId { get; set; }
        public int? CreationTransactionItemId { get; set; }
        public int? ReservedPieces { get; set; }
        public decimal? ReservedWeight { get; set; }
        public decimal? ReservedQuantity { get; set; }
        public DateTime? HoldDate { get; set; }
        public int? HoldReasonId { get; set; }
        public string HoldDescription { get; set; }
        public int? HoldUserId { get; set; }
        public int? PurchaseItemId { get; set; }
        public string SpecificationValue6 { get; set; }
        public string SpecificationValue7 { get; set; }
        public string SpecificationValue8 { get; set; }
        public string SpecificationValue9 { get; set; }
        public string SpecificationValue10 { get; set; }
        public int? Specification1Id { get; set; }
        public int? Specification2Id { get; set; }
        public int? Specification3Id { get; set; }
        public int? Specification4Id { get; set; }
        public int? Specification5Id { get; set; }
        public int? Specification6Id { get; set; }
        public int? Specification7Id { get; set; }
        public int? Specification8Id { get; set; }
        public int? Specification9Id { get; set; }
        public int? Specification10Id { get; set; }
        public int? Dim1TypeId { get; set; }
        public int? Dim2TypeId { get; set; }
        public int? Dim3TypeId { get; set; }
        public int? Dim4TypeId { get; set; }
        public int? Dim5TypeId { get; set; }
        public bool? CustomersOwn { get; set; }
        public DateTime? LastCheckedDate { get; set; }
        public DateTime? FixDate { get; set; }
        public bool? NonTraceable { get; set; }
        public string CertificateOfConformityReference { get; set; }
        public string TestNumber { get; set; }
        public string TreatmentNumber { get; set; }
        public decimal? DutyPercentage { get; set; }
        public DateTime EtlcreateDate { get; set; }
        public DateTime EtlupdateDate { get; set; }
        public DateTime? StorageDate { get; set; }
        public DateTime? AgedDate { get; set; }
        public DateTime? IncomingDate { get; set; }
        public bool? Printed { get; set; }
    }
}
