using System;
using System.Collections.Generic;

namespace BI.DAL.DataWarehouse.Core.Models
{
    public partial class Products
    {
        public string Coid { get; set; }
        public int Id { get; set; }
        public int? Version { get; set; }
        public DateTime? Cdate { get; set; }
        public DateTime? Mdate { get; set; }
        public int? CuserId { get; set; }
        public int? MuserId { get; set; }
        public string Status { get; set; }
        public int? BuyerId { get; set; }
        public int? CategoryId { get; set; }
        public string Code { get; set; }
        public string OtherCode { get; set; }
        public string Size { get; set; }
        public int? GradeId { get; set; }
        public string Sequence { get; set; }
        public string Description { get; set; }
        public string SizeDescription { get; set; }
        public bool? SizeInDescription { get; set; }
        public decimal? Density { get; set; }
        public int? IdentifyingMarkId { get; set; }
        public int? Analysis1Id { get; set; }
        public int? Analysis2Id { get; set; }
        public int? Analysis3Id { get; set; }
        public int? Analysis4Id { get; set; }
        public int? VatType1Id { get; set; }
        public int? VatType2Id { get; set; }
        public int? VatType3Id { get; set; }
        public int? VatType4Id { get; set; }
        public int? CommodityId { get; set; }
        public decimal? Dim1StaticDimension { get; set; }
        public decimal? Dim1MinimumOffcut { get; set; }
        public decimal? Dim2StaticDimension { get; set; }
        public decimal? Dim2MinimumOffcut { get; set; }
        public decimal? Dim3StaticDimension { get; set; }
        public decimal? Dim3MinimumOffcut { get; set; }
        public decimal? Dim4StaticDimension { get; set; }
        public decimal? Dim4MinimumOffcut { get; set; }
        public decimal? Dim5StaticDimension { get; set; }
        public decimal? Dim5MinimumOffcut { get; set; }
        public string Notes { get; set; }
        public string SpecificationValue1 { get; set; }
        public string SpecificationValue2 { get; set; }
        public string SpecificationValue3 { get; set; }
        public string SpecificationValue4 { get; set; }
        public string SpecificationValue5 { get; set; }
        public int? SalesCostingTypeId { get; set; }
        public int? EnquiryCostShownId { get; set; }
        public int? SourceProductId { get; set; }
        public decimal? StandardCost { get; set; }
        public int? SalesGroupId { get; set; }
        public int? MinimumGradeId { get; set; }
        public string DescriptionFormula { get; set; }
        public decimal? MinimumMargin { get; set; }
        public string SalesNotes { get; set; }
        public string PurchaseNotes { get; set; }
        public string SpecificationValue6 { get; set; }
        public string SpecificationValue7 { get; set; }
        public string SpecificationValue8 { get; set; }
        public string SpecificationValue9 { get; set; }
        public string SpecificationValue10 { get; set; }
        public int? PurchaseGroupId { get; set; }
        public bool? Dim1ProductionOverride { get; set; }
        public bool? Dim2ProductionOverride { get; set; }
        public bool? Dim3ProductionOverride { get; set; }
        public bool? Dim4ProductionOverride { get; set; }
        public bool? Dim5ProductionOverride { get; set; }
        public bool? RequireCertification { get; set; }
        public int? AlternateProductId { get; set; }
        public int? Specification1Id { get; set; }
        public int? Specification2Id { get; set; }
        public int? Specification3Id { get; set; }
        public int? Specification4Id { get; set; }
        public int? Specification5Id { get; set; }
        public int? Specification6Id { get; set; }
        public int? Specification7Id { get; set; }
        public int? Specification8Id { get; set; }
        public int? Specification9Id { get; set; }
        public int? Specification10Id { get; set; }
        public int? Dim1TypeId { get; set; }
        public int? Dim2TypeId { get; set; }
        public int? Dim3TypeId { get; set; }
        public int? Dim4TypeId { get; set; }
        public int? Dim5TypeId { get; set; }
        public string LedgerSegmentCode { get; set; }
        public int? DefaultStockStatusId { get; set; }
        public string TestingNotes { get; set; }
        public int? CuttingGroupCostId { get; set; }
        public decimal? GuideCost { get; set; }
        public decimal? GuidePrice { get; set; }
        public decimal? FabricationPrice { get; set; }
        public int? ScrapProductId { get; set; }
        public decimal? Dim1NegativeTolerance { get; set; }
        public decimal? Dim1PositiveTolerance { get; set; }
        public decimal? Dim2NegativeTolerance { get; set; }
        public decimal? Dim2PositiveTolerance { get; set; }
        public decimal? Dim3NegativeTolerance { get; set; }
        public decimal? Dim3PositiveTolerance { get; set; }
        public decimal? Dim4NegativeTolerance { get; set; }
        public decimal? Dim4PositiveTolerance { get; set; }
        public decimal? Dim5NegativeTolerance { get; set; }
        public decimal? Dim5PositiveTolerance { get; set; }
        public bool? NonTraceableUsesLocation { get; set; }
        public decimal? Dim1Kerf { get; set; }
        public decimal? Dim2Kerf { get; set; }
        public decimal? Dim3Kerf { get; set; }
        public decimal? Dim4Kerf { get; set; }
        public decimal? Dim5Kerf { get; set; }
        public DateTime? EtlcreateDate { get; set; }
        public DateTime? EtlupdateDate { get; set; }
        public bool? DefaultConsumedDimInProduction1 { get; set; }
        public bool? DefaultConsumedDimInProduction2 { get; set; }
        public bool? DefaultConsumedDimInProduction3 { get; set; }
        public bool? DefaultConsumedDimInProduction4 { get; set; }
        public bool? DefaultConsumedDimInProduction5 { get; set; }
        public decimal? NestingGap { get; set; }
        public int? NestingGapUnitsId { get; set; }
        public int? DefaultEnquiryCostingTypeId { get; set; }
        public bool? ApplyHeaderCostsAndCharges { get; set; }
    }
}
