using System;
using System.Collections.Generic;

namespace BI.DAL.DataWarehouse.Core.Models
{
    public partial class ProductCategories
    {
        public string Coid { get; set; }
        public int Id { get; set; }
        public int? Version { get; set; }
        public DateTime? Cdate { get; set; }
        public DateTime? Mdate { get; set; }
        public int? CuserId { get; set; }
        public int? MuserId { get; set; }
        public string Status { get; set; }
        public int? PurchaseGroupId { get; set; }
        public string Category { get; set; }
        public string Base { get; set; }
        public string Form { get; set; }
        public int? ProductControlId { get; set; }
        public int? SequenceNumber { get; set; }
        public string Description { get; set; }
        public decimal? VolumeDensity { get; set; }
        public int? StockTypeId { get; set; }
        public int? Analysis1Id { get; set; }
        public int? Analysis2Id { get; set; }
        public int? VatType1Id { get; set; }
        public int? VatType2Id { get; set; }
        public int? VatType3Id { get; set; }
        public int? VatType4Id { get; set; }
        public bool? DynamicDensity { get; set; }
        public bool? AverageCost { get; set; }
        public int? QuantityEntryId { get; set; }
        public bool? ManualGuideCost { get; set; }
        public int? SalesNominalId { get; set; }
        public int? SalesCostCentreId { get; set; }
        public int? CostNominalId { get; set; }
        public int? CostCostCentreId { get; set; }
        public int? StockNominalId { get; set; }
        public int? StockCostCentreId { get; set; }
        public int? PriceUnitId { get; set; }
        public int? BuyUnitId { get; set; }
        public int? CostUnitId { get; set; }
        public int? SalesQuantityUnitId { get; set; }
        public int? BuyingQuantityUnitId { get; set; }
        public int? PriceDecimals { get; set; }
        public string PiecesLabel { get; set; }
        public string PiecesPluralLabel { get; set; }
        public int? DefaultStockStatusId { get; set; }
        public int? SourceCategoryId { get; set; }
        public int? Specification1Id { get; set; }
        public bool? ValidateSpecification1 { get; set; }
        public int? Specification2Id { get; set; }
        public bool? ValidateSpecification2 { get; set; }
        public int? Specification3Id { get; set; }
        public bool? ValidateSpecification3 { get; set; }
        public int? Specification4Id { get; set; }
        public bool? ValidateSpecification4 { get; set; }
        public int? Specification5Id { get; set; }
        public bool? ValidateSpecification5 { get; set; }
        public bool? Dim1GrainFlow { get; set; }
        public decimal? Dim1PositiveTolerance { get; set; }
        public decimal? Dim1NegativeTolerance { get; set; }
        public int? Dim1Decimals { get; set; }
        public bool? Dim1UseInDescription { get; set; }
        public bool? Dim1UseDimName { get; set; }
        public bool? Dim2GrainFlow { get; set; }
        public decimal? Dim2PositiveTolerance { get; set; }
        public decimal? Dim2NegativeTolerance { get; set; }
        public int? Dim2Decimals { get; set; }
        public bool? Dim2UseInDescription { get; set; }
        public bool? Dim2UseDimName { get; set; }
        public bool? Dim3GrainFlow { get; set; }
        public decimal? Dim3PositiveTolerance { get; set; }
        public decimal? Dim3NegativeTolerance { get; set; }
        public int? Dim3Decimals { get; set; }
        public bool? Dim3UseInDescription { get; set; }
        public bool? Dim3UseDimName { get; set; }
        public bool? Dim4GrainFlow { get; set; }
        public decimal? Dim4PositiveTolerance { get; set; }
        public decimal? Dim4NegativeTolerance { get; set; }
        public int? Dim4Decimals { get; set; }
        public bool? Dim4UseInDescription { get; set; }
        public bool? Dim4UseDimName { get; set; }
        public bool? Dim5GrainFlow { get; set; }
        public decimal? Dim5PositiveTolerance { get; set; }
        public decimal? Dim5NegativeTolerance { get; set; }
        public int? Dim5Decimals { get; set; }
        public bool? Dim5UseInDescription { get; set; }
        public bool? Dim5UseDimName { get; set; }
        public int? SalesCostingTypeId { get; set; }
        public int? EnquiryCostShownId { get; set; }
        public int? SpecificationTemplateId { get; set; }
        public int? SalesGroupId { get; set; }
        public string ChargeBasis { get; set; }
        public decimal? MinimumMargin { get; set; }
        public decimal? DespatchAllocationVariance { get; set; }
        public bool? CategoryLevelTaxes { get; set; }
        public bool? PrintSpecification1 { get; set; }
        public bool? PrintSpecification2 { get; set; }
        public bool? PrintSpecification3 { get; set; }
        public bool? PrintSpecification4 { get; set; }
        public bool? PrintSpecification5 { get; set; }
        public int? Specification6Id { get; set; }
        public bool? ValidateSpecification6 { get; set; }
        public bool? PrintSpecification6 { get; set; }
        public int? Specification7Id { get; set; }
        public bool? ValidateSpecification7 { get; set; }
        public bool? PrintSpecification7 { get; set; }
        public int? Specification8Id { get; set; }
        public bool? ValidateSpecification8 { get; set; }
        public bool? PrintSpecification8 { get; set; }
        public int? Specification9Id { get; set; }
        public bool? ValidateSpecification9 { get; set; }
        public bool? PrintSpecification9 { get; set; }
        public int? Specification10Id { get; set; }
        public bool? ValidateSpecification10 { get; set; }
        public bool? PrintSpecification10 { get; set; }
        public bool? Dim1Print { get; set; }
        public bool? Dim2Print { get; set; }
        public bool? Dim3Print { get; set; }
        public bool? Dim4Print { get; set; }
        public bool? Dim5Print { get; set; }
        public bool? RequireCertification { get; set; }
        public bool? MandatorySpecification1 { get; set; }
        public bool? MandatorySpecification2 { get; set; }
        public bool? MandatorySpecification3 { get; set; }
        public bool? MandatorySpecification4 { get; set; }
        public bool? MandatorySpecification5 { get; set; }
        public bool? MandatorySpecification6 { get; set; }
        public bool? MandatorySpecification7 { get; set; }
        public bool? MandatorySpecification8 { get; set; }
        public bool? MandatorySpecification9 { get; set; }
        public bool? MandatorySpecification10 { get; set; }
        public string LedgerSegmentCode { get; set; }
        public int? ProductionQuantityEntryId { get; set; }
        public bool? SpecificationCheck { get; set; }
        public bool? AutoAllocate { get; set; }
        public bool? ProductionMixedCastsAllowed { get; set; }
        public bool? FlagStockItemsWithNotes { get; set; }
        public bool? NonTraceable { get; set; }
        public int? OrderQuantityEntryId { get; set; }
        public bool? ValidateDynamicDensity { get; set; }
        public bool? InvoiceWeightUpdatesItemBalance { get; set; }
        public decimal? Dim1Kerf { get; set; }
        public decimal? Dim2Kerf { get; set; }
        public decimal? Dim3Kerf { get; set; }
        public decimal? Dim4Kerf { get; set; }
        public decimal? Dim5Kerf { get; set; }
        public DateTime? EtlcreateDate { get; set; }
        public DateTime? EtlupdateDate { get; set; }
        public int? GoodsInwardsQuantityEntryId { get; set; }
        public int? SalesPriceUnitId { get; set; }
        public int DefaultQuantityDisplayFormat { get; set; }
        public int DefaultDimensionDescriptionFormat1 { get; set; }
        public int DefaultDimensionDescriptionFormat2 { get; set; }
        public int DefaultDimensionDescriptionFormat3 { get; set; }
        public int DefaultDimensionDescriptionFormat4 { get; set; }
        public int DefaultDimensionDescriptionFormat5 { get; set; }
        public decimal? GuideCostUpliftPercentage { get; set; }
        public bool? NonTraceableFlagOnSubGroups { get; set; }
    }
}
