using System;
using System.Collections.Generic;

namespace BI.DAL.DataWarehouse.Core.Models
{
    public partial class SageVApven
    {
        public string Coid { get; set; }
        public string Vendorid { get; set; }
        public decimal Audtdate { get; set; }
        public decimal Audttime { get; set; }
        public string Audtuser { get; set; }
        public string Audtorg { get; set; }
        public string Shortname { get; set; }
        public string Idgrp { get; set; }
        public short Swactv { get; set; }
        public decimal Dateinac { get; set; }
        public decimal Datelastmn { get; set; }
        public short Swhold { get; set; }
        public decimal Datestart { get; set; }
        public string Idppnt { get; set; }
        public string Vendname { get; set; }
        public string Textstre1 { get; set; }
        public string Textstre2 { get; set; }
        public string Textstre3 { get; set; }
        public string Textstre4 { get; set; }
        public string Namecity { get; set; }
        public string Codestte { get; set; }
        public string Codepstl { get; set; }
        public string Codectry { get; set; }
        public string Namectac { get; set; }
        public string Textphon1 { get; set; }
        public string Textphon2 { get; set; }
        public string Primrmit { get; set; }
        public string Idacctset { get; set; }
        public string Curncode { get; set; }
        public string Ratetype { get; set; }
        public string Bankid { get; set; }
        public short Prtsepchks { get; set; }
        public string Distsetid { get; set; }
        public string Distcode { get; set; }
        public string Glaccnt { get; set; }
        public string Termscode { get; set; }
        public short Dupinvccd { get; set; }
        public short Dupamtcode { get; set; }
        public short Dupdatecd { get; set; }
        public string Codetaxgrp { get; set; }
        public short Taxclass1 { get; set; }
        public short Taxclass2 { get; set; }
        public short Taxclass3 { get; set; }
        public short Taxclass4 { get; set; }
        public short Taxclass5 { get; set; }
        public short Taxrptsw { get; set; }
        public short Subjtowthh { get; set; }
        public string Taxnbr { get; set; }
        public short Taxidtype { get; set; }
        public short Taxnote2sw { get; set; }
        public string Clasid { get; set; }
        public decimal Amtcrlimt { get; set; }
        public decimal Amtbalduet { get; set; }
        public decimal Amtbaldueh { get; set; }
        public decimal Amtppdinvt { get; set; }
        public decimal Amtppdinvh { get; set; }
        public decimal Dtlastrval { get; set; }
        public decimal Amtballarv { get; set; }
        public decimal Cntopeninv { get; set; }
        public decimal Cntppdinvc { get; set; }
        public decimal Cntinvpaid { get; set; }
        public decimal Daystopay { get; set; }
        public decimal Dateinvchi { get; set; }
        public decimal Datebalhi { get; set; }
        public decimal Dateinvhil { get; set; }
        public decimal Datebalhil { get; set; }
        public decimal Datelastac { get; set; }
        public decimal Datelastiv { get; set; }
        public decimal Datelastcr { get; set; }
        public decimal Datelastdr { get; set; }
        public decimal Datelastpa { get; set; }
        public decimal Datelastdi { get; set; }
        public decimal Datelstadj { get; set; }
        public string Idinvchi { get; set; }
        public string Idinvchily { get; set; }
        public decimal Amtinvhit { get; set; }
        public decimal Amtbalhit { get; set; }
        public decimal Amtwthtcur { get; set; }
        public decimal Amtinvhilt { get; set; }
        public decimal Amtbalhilt { get; set; }
        public decimal Amtwthlytc { get; set; }
        public decimal Amtlastivt { get; set; }
        public decimal Amtlastcrt { get; set; }
        public decimal Amtlastdrt { get; set; }
        public decimal Amtlastpyt { get; set; }
        public decimal Amtlastdit { get; set; }
        public decimal Amtlastadt { get; set; }
        public decimal Amtinvhih { get; set; }
        public decimal Amtbalhih { get; set; }
        public decimal Amtwthhcur { get; set; }
        public decimal Amtinvhilh { get; set; }
        public decimal Amtbalhilh { get; set; }
        public decimal Amtwthlyhc { get; set; }
        public decimal Amtlastivh { get; set; }
        public decimal Amtlastcrh { get; set; }
        public decimal Amtlastdrh { get; set; }
        public decimal Amtlastpyh { get; set; }
        public decimal Amtlastdih { get; set; }
        public decimal Amtlastadh { get; set; }
        public string Paymcode { get; set; }
        public string Idtaxregi1 { get; set; }
        public string Idtaxregi2 { get; set; }
        public string Idtaxregi3 { get; set; }
        public string Idtaxregi4 { get; set; }
        public string Idtaxregi5 { get; set; }
        public short Swdistby { get; set; }
        public string Codecheck { get; set; }
        public decimal Avgdayspay { get; set; }
        public decimal Avgpayment { get; set; }
        public decimal Amtinvpdhc { get; set; }
        public decimal Amtinvpdtc { get; set; }
        public decimal Cntnbrchks { get; set; }
        public short Swtxinc1 { get; set; }
        public short Swtxinc2 { get; set; }
        public short Swtxinc3 { get; set; }
        public short Swtxinc4 { get; set; }
        public short Swtxinc5 { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string Website { get; set; }
        public string Ctacphone { get; set; }
        public string Ctacfax { get; set; }
        public short Delmethod { get; set; }
        public decimal Rtgpercent { get; set; }
        public short Rtgdays { get; set; }
        public string Rtgterms { get; set; }
        public decimal Rtgamttc { get; set; }
        public decimal Rtgamthc { get; set; }
        public int Values { get; set; }
        public int Nextcuid { get; set; }
        public string Legalname { get; set; }
        public short Chk1099amt { get; set; }
        public string Idcust { get; set; }
        public string Brn { get; set; }
    }
}
