using System;
using System.Collections.Generic;

namespace BI.DAL.DataWarehouse.Core.Models
{
    public partial class SalesHeaders
    {
        public string Coid { get; set; }
        public int Id { get; set; }
        public int? Version { get; set; }
        public DateTime? Cdate { get; set; }
        public DateTime? Mdate { get; set; }
        public int? CuserId { get; set; }
        public int? MuserId { get; set; }
        public string Status { get; set; }
        public int? BranchId { get; set; }
        public int? Number { get; set; }
        public string CustomerOrderNumber { get; set; }
        public string JobNumber { get; set; }
        public string ReleaseNumber { get; set; }
        public int? CustomerId { get; set; }
        public string CustomerNameOverride { get; set; }
        public int? CustomerAddressId { get; set; }
        public int? DeliverToId { get; set; }
        public int? DeliverToAddressId { get; set; }
        public int? SalespersonId { get; set; }
        public int? InsideSalespersonId { get; set; }
        public int? DeliveryBranchId { get; set; }
        public int? DeliveryWarehouseId { get; set; }
        public string DeliveryName { get; set; }
        public int? DeliveryAddressId { get; set; }
        public int? StatusId { get; set; }
        public int? TypeId { get; set; }
        public DateTime? SaleDate { get; set; }
        public DateTime? DueDate { get; set; }
        public string ManualDate { get; set; }
        public int? TransportTypeId { get; set; }
        public string DeliveryPoint { get; set; }
        public int? CarrierId { get; set; }
        public decimal? TransportCostRate { get; set; }
        public int? TransportCostRateUnitId { get; set; }
        public decimal? TransportCostAmount { get; set; }
        public decimal? TransportExchangeRate { get; set; }
        public int? TransportExchangeRateTypeId { get; set; }
        public bool? Acknowledged { get; set; }
        public DateTime? AcknowledgedDate { get; set; }
        public bool? Printed { get; set; }
        public int? CurrencyId { get; set; }
        public decimal? ExchangeRate { get; set; }
        public int? ExchangeRateTypeId { get; set; }
        public int? TermsId { get; set; }
        public decimal? SettlementDiscount { get; set; }
        public int? CertificationsId { get; set; }
        public string HeaderText { get; set; }
        public string InternalText { get; set; }
        public string DespatchText { get; set; }
        public bool? Completed { get; set; }
        public DateTime? CompletedDate { get; set; }
        public int? InvoiceNumber { get; set; }
        public DateTime? PaymentDueDate { get; set; }
        public int? CreditedInvoiceBranchId { get; set; }
        public int? CreditedInvoice { get; set; }
        public string CreditReference { get; set; }
        public int? OrderId { get; set; }
        public string DeliverToNameOverride { get; set; }
        public decimal? TransportChargeRate { get; set; }
        public int? TransportChargeRateUnitId { get; set; }
        public decimal? TransportChargeAmount { get; set; }
        public int? BatchId { get; set; }
        public int? LostReasonId { get; set; }
        public DateTime? LostDate { get; set; }
        public string LostDescription { get; set; }
        public int? DespatchId { get; set; }
        public DateTime? FollowupDate { get; set; }
        public int? SalesTotalId { get; set; }
        public DateTime? PrintedDate { get; set; }
        public string Discriminator { get; set; }
        public bool? CreditHold { get; set; }
        public DateTime? CreditHoldDate { get; set; }
        public int? CreditHoldReason { get; set; }
        public DateTime? CreditReleaseDate { get; set; }
        public int? CreditReleaseUserId { get; set; }
        public decimal? CreditReleaseAmount { get; set; }
        public int? GatewayBatchId { get; set; }
        public DateTime? ExportedDate { get; set; }
        public bool? UpdateHold { get; set; }
        public int? EnquiryId { get; set; }
        public bool? UseMinimumGrade { get; set; }
        public int? SalesEntryTotalId { get; set; }
        public int? CreditedDespatchBranchId { get; set; }
        public int? CreditedDespatch { get; set; }
        public int? CreditedOrderBranchId { get; set; }
        public int? CreditedOrder { get; set; }
        public string CreditReleaseNotes { get; set; }
        public int? BalanceTotalId { get; set; }
        public bool? RequireProforma { get; set; }
        public DateTime? ProformaPrintedDate { get; set; }
        public int? VatType1Id { get; set; }
        public int? VatType2Id { get; set; }
        public int? VatType3Id { get; set; }
        public int? VatType4Id { get; set; }
        public string TransferType { get; set; }
        public string TaxGroupCode { get; set; }
        public int? TaxClass1 { get; set; }
        public int? TaxClass2 { get; set; }
        public int? TaxClass3 { get; set; }
        public int? TaxClass4 { get; set; }
        public int? TaxClass5 { get; set; }
        public int? TransferToBranchId { get; set; }
        public int? TransferToWarehouseId { get; set; }
        public string TaxAuthority1 { get; set; }
        public string TaxAuthority2 { get; set; }
        public string TaxAuthority3 { get; set; }
        public string TaxAuthority4 { get; set; }
        public string TaxAuthority5 { get; set; }
        public bool? TaxExempt1 { get; set; }
        public bool? TaxExempt2 { get; set; }
        public bool? TaxExempt3 { get; set; }
        public bool? TaxExempt4 { get; set; }
        public bool? TaxExempt5 { get; set; }
        public int? DocumentDeliveryTypeId { get; set; }
        public int? ContactId { get; set; }
        public string ContactTelephoneOverride { get; set; }
        public string ContactMobileOverride { get; set; }
        public string ContactFaxOverride { get; set; }
        public string ContactEmailOverride { get; set; }
        public string ContactWebAddressOverride { get; set; }
        public int? CuttingHeaderId { get; set; }
        public string FooterInternalText { get; set; }
        public string FooterExternalText { get; set; }
        public int? BlanketHeaderId { get; set; }
        public bool TransportCharged { get; set; }
        public DateTime? FixDate { get; set; }
        public DateTime? ExpiryDate { get; set; }
        public bool? NoFixedDate { get; set; }
        public DateTime? CreditedDeliveryDate { get; set; }
        public bool CreditHeldAtDespatch { get; set; }
        public bool ConsignmentOrder { get; set; }
        public int? ImportBatchNumber { get; set; }
        public string ImportSource { get; set; }
        public int? ImportNumber { get; set; }
        public int? LostReasonValue { get; set; }
        public int? SalesGroupId { get; set; }
        public decimal? LocalExchangeRate { get; set; }
        public int? CommercialTermsId { get; set; }
        public int? OrderClassificationId { get; set; }
        public decimal? InvoiceBaseCurrencyExchangeRate { get; set; }
        public DateTime? WorkOrderPrintedDate { get; set; }
        public DateTime? SalesOrderPrintedDate { get; set; }
        public DateTime? SignOffPrintedDate { get; set; }
        public DateTime? TransportPrintedDate { get; set; }
        public DateTime? WeighbridgePrintedDate { get; set; }
        public DateTime? YardOrderPrintedDate { get; set; }
        public DateTime? TravelCardPrintedDate { get; set; }
        public bool? CounterSales { get; set; }
        public decimal? BalanceToPay { get; set; }
        public string ImportUserName { get; set; }
        public int? SalesExportDetailsId { get; set; }
        public int? DiscountDays { get; set; }
        public DateTime? DiscountDate { get; set; }
        public decimal? DiscountPercentage { get; set; }
        public int? ContractJobId { get; set; }
        public decimal? TransportChargeTax { get; set; }
        public int? ProjectTypeId { get; set; }
        public int? FinalDestinationId { get; set; }
        public int? QuoteVersionId { get; set; }
        public int? DuplicateReasonId { get; set; }
        public int? QuotationTypeId { get; set; }
    }
}
