using System;
using System.Collections.Generic;

namespace BI.DAL.DataWarehouse.Core.Models
{
    public partial class SalesItems
    {
        public string Coid { get; set; }
        public int Id { get; set; }
        public int Version { get; set; }
        public DateTime Cdate { get; set; }
        public DateTime Mdate { get; set; }
        public int CuserId { get; set; }
        public int MuserId { get; set; }
        public string Status { get; set; }
        public int? SalesHeaderId { get; set; }
        public int? ItemNumber { get; set; }
        public int? ProductId { get; set; }
        public int? DimensionsId { get; set; }
        public string Description { get; set; }
        public string WorksNotes { get; set; }
        public string ProductionNotes { get; set; }
        public string InvoiceNotes { get; set; }
        public int? RequiredPieces { get; set; }
        public decimal? RequiredQuantity { get; set; }
        public decimal? RequiredWeight { get; set; }
        public int? DeliveredPieces { get; set; }
        public decimal? DeliveredQuantity { get; set; }
        public decimal? DeliveredWeight { get; set; }
        public int? BalancePieces { get; set; }
        public decimal? BalanceQuantity { get; set; }
        public decimal? BalanceWeight { get; set; }
        public int? WeightUnitsId { get; set; }
        public int? PartCustomerId { get; set; }
        public int? PartSpecificationId { get; set; }
        public int? StatusId { get; set; }
        public int? SalesGroupId { get; set; }
        public int? VatType1Id { get; set; }
        public int? VatType2Id { get; set; }
        public int? VatType3Id { get; set; }
        public int? VatType4Id { get; set; }
        public DateTime? DueDate { get; set; }
        public string ManualDate { get; set; }
        public bool? Completed { get; set; }
        public DateTime? CompletedDate { get; set; }
        public string SpecificationValue1 { get; set; }
        public string SpecificationValue2 { get; set; }
        public string SpecificationValue3 { get; set; }
        public string SpecificationValue4 { get; set; }
        public string SpecificationValue5 { get; set; }
        public int? CreditedItem { get; set; }
        public string CreditReference { get; set; }
        public int? DespatchItemId { get; set; }
        public int? OrderItemId { get; set; }
        public int? DeliveryBranchId { get; set; }
        public int? DeliveryWarehouseId { get; set; }
        public int? LostReasonId { get; set; }
        public DateTime? LostDate { get; set; }
        public string LostDescription { get; set; }
        public int? SalesTotalId { get; set; }
        public string Discriminator { get; set; }
        public decimal? OriginalQuantity { get; set; }
        public int? OriginalQuantityUnitId { get; set; }
        public DateTime? OriginalDueDate { get; set; }
        public int? TransportPieces { get; set; }
        public decimal? TransportQuantity { get; set; }
        public decimal? TransportWeight { get; set; }
        public bool? ShowPrices { get; set; }
        public bool? UseMinimumGrade { get; set; }
        public string StockLocation { get; set; }
        public int? InvoicedPieces { get; set; }
        public decimal? InvoicedQuantity { get; set; }
        public decimal? InvoicedWeight { get; set; }
        public string MarginType { get; set; }
        public int? BalanceTotalId { get; set; }
        public int? AllocatedPieces { get; set; }
        public decimal? AllocatedQuantity { get; set; }
        public decimal? AllocatedWeight { get; set; }
        public string TransferType { get; set; }
        public int? TaxClass1 { get; set; }
        public int? TaxClass2 { get; set; }
        public int? TaxClass3 { get; set; }
        public int? TaxClass4 { get; set; }
        public int? TaxClass5 { get; set; }
        public bool? TaxExempt1 { get; set; }
        public bool? TaxExempt2 { get; set; }
        public bool? TaxExempt3 { get; set; }
        public bool? TaxExempt4 { get; set; }
        public bool? TaxExempt5 { get; set; }
        public string PartNumber { get; set; }
        public string SpecificationValue6 { get; set; }
        public string SpecificationValue7 { get; set; }
        public string SpecificationValue8 { get; set; }
        public string SpecificationValue9 { get; set; }
        public string SpecificationValue10 { get; set; }
        public int? ProductLevelAllocationId { get; set; }
        public decimal? OutsideDiameter { get; set; }
        public decimal? OutsideDiameterMinimum { get; set; }
        public decimal? OutsideDiameterMaximum { get; set; }
        public decimal? PackHeight { get; set; }
        public decimal? PackHeightMinimum { get; set; }
        public decimal? PackHeightMaximum { get; set; }
        public decimal? PackWeight { get; set; }
        public decimal? PackWeightMinimum { get; set; }
        public decimal? PackWeightMaximum { get; set; }
        public decimal? InsideDiameter { get; set; }
        public decimal? InsideDiameterMinimum { get; set; }
        public decimal? InsideDiameterMaximum { get; set; }
        public bool? TrimRequired { get; set; }
        public bool? ShotblastingRequired { get; set; }
        public string PaintDescription { get; set; }
        public int? GroupPriceUnitId { get; set; }
        public decimal? GroupTotalPrice { get; set; }
        public decimal? GroupTotalValue { get; set; }
        public int? AllocatedCoilPieces { get; set; }
        public int? PackCountMinimum { get; set; }
        public int? PackCountMaximum { get; set; }
        public decimal? WorkOrderPrintedQuantity { get; set; }
        public string ProductDescription { get; set; }
        public decimal? InvoiceCostingWeight { get; set; }
        public int? WorkingSpecificationId { get; set; }
        public int? CallOffPieces { get; set; }
        public decimal? CallOffQuantity { get; set; }
        public decimal? CallOffWeight { get; set; }
        public int? BlanketItemId { get; set; }
        public int? CreditedOrderNumber { get; set; }
        public int? CreditedOrderItem { get; set; }
        public int? CreditedDespatchItem { get; set; }
        public int? PaintTypeId { get; set; }
        public bool? StockAvailable { get; set; }
        public decimal? MixturePrice { get; set; }
        public decimal? FabricationPrice { get; set; }
        public decimal? AdjustmentPrice { get; set; }
        public decimal? YieldPercentage { get; set; }
        public string CreditedCustomerOrder { get; set; }
        public bool? CalculatePieces { get; set; }
        public decimal? StandardPrice { get; set; }
        public string CuttingGroupReference { get; set; }
        public bool? CompleteAfterNextInvoice { get; set; }
        public decimal? CompletionBalanceQuantity { get; set; }
        public bool? MechanicalCert { get; set; }
        public bool? ShowCountryOfMaterialOrigin { get; set; }
        public bool? ShowCountryOfPrimaryProcessing { get; set; }
        public bool? ShowCountryOfFinalProcessing { get; set; }
        public bool? ItemCredited { get; set; }
        public string AcknowledgementNotes { get; set; }
        public string DespatchNotes { get; set; }
        public bool? FullyAllocated { get; set; }
        public bool? InvoicePacking { get; set; }
        public decimal? GroupCuttingCost { get; set; }
        public int? GroupCuttingCostUnitId { get; set; }
        public decimal? GroupDrillingCost { get; set; }
        public int? GroupDrillingCostUnitId { get; set; }
        public decimal? GroupPaintingCost { get; set; }
        public int? GroupPaintingCostUnitId { get; set; }
        public decimal? GroupShotblastingCost { get; set; }
        public int? GroupShotblastingCostUnitId { get; set; }
        public int? ProductSubGroupId { get; set; }
        public decimal? GroupConsumptionPrice { get; set; }
        public int? ImportBatchNumber { get; set; }
        public int? ImportNumber { get; set; }
        public int? ImportItem { get; set; }
        public int? LostReasonValue { get; set; }
        public decimal? FlatRolledValue { get; set; }
        public bool? FlatRolled { get; set; }
        public int? OldestPurchaseOrderNumber { get; set; }
        public string IntercompanyPurchaseBranch { get; set; }
        public int? IntercompanyPurchaseOrder { get; set; }
        public int? IntercompanyPurchaseItem { get; set; }
        public DateTime EtlcreateDate { get; set; }
        public DateTime EtlupdateDate { get; set; }
        public bool? FromFlatRolled { get; set; }
        public string OptimisationType { get; set; }
        public bool WorksOrderNotRequiredAfterProduction { get; set; }
        public int? FabricationProcessId { get; set; }
        public int? FabricationWorkCentreId { get; set; }
        public int? FabricationId { get; set; }
        public int? PriceBookId { get; set; }
        public int? PriceBookLevel { get; set; }
        public int? PriceBookQuantityBreak { get; set; }
        public int? InvoicedSalesItemId { get; set; }
        public DateTime? RequiredQuantityChangeTimestamp { get; set; }
        public int? SecantOptimiserResultId { get; set; }
        public bool? MlcConversionAllowed { get; set; }
    }
}
