using System;
using System.Collections.Generic;

namespace BI.DAL.DataWarehouse.Core.Models
{
    public partial class SalesAnalysisDetails
    {
        public string Coid { get; set; }
        public int Id { get; set; }
        public int Version { get; set; }
        public DateTime? Cdate { get; set; }
        public DateTime? Mdate { get; set; }
        public int CuserId { get; set; }
        public int MuserId { get; set; }
        public string Status { get; set; }
        public int? BranchId { get; set; }
        public int? ReferenceNumber { get; set; }
        public int? ItemNumber { get; set; }
        public int? OrderNumber { get; set; }
        public int? OrderItemNumber { get; set; }
        public int? DespatchNumber { get; set; }
        public int? DespatchItemNumber { get; set; }
        public string CustomerOrderNumber { get; set; }
        public string JobNumber { get; set; }
        public string ReleaseNumber { get; set; }
        public int? CustomerId { get; set; }
        public int? ProductId { get; set; }
        public decimal? Dim1 { get; set; }
        public decimal? Dim2 { get; set; }
        public decimal? Dim3 { get; set; }
        public decimal? Dim4 { get; set; }
        public decimal? Dim5 { get; set; }
        public int? DeliveryBranchId { get; set; }
        public int? DeliveryWarehouseId { get; set; }
        public string Description { get; set; }
        public int? SalesGroupId { get; set; }
        public int? PartCustomerId { get; set; }
        public int? PartSpecificationId { get; set; }
        public int? Pieces { get; set; }
        public decimal? Quantity { get; set; }
        public decimal? Weight { get; set; }
        public decimal? MaterialCharge { get; set; }
        public decimal? TransportCharge { get; set; }
        public decimal? ProductionCharge { get; set; }
        public decimal? MiscellaneousCharge { get; set; }
        public decimal? SurchargeCharge { get; set; }
        public decimal? MaterialDiscount { get; set; }
        public decimal? TransportDiscount { get; set; }
        public decimal? ProductionDiscount { get; set; }
        public decimal? MiscellaneousDiscount { get; set; }
        public decimal? SurchargeDiscount { get; set; }
        public decimal? MaterialValue { get; set; }
        public decimal? TransportValue { get; set; }
        public decimal? ProductionValue { get; set; }
        public decimal? MiscellaneousValue { get; set; }
        public decimal? SurchargeValue { get; set; }
        public decimal? MaterialCost { get; set; }
        public decimal? TransportCost { get; set; }
        public decimal? ProductionCost { get; set; }
        public decimal? MiscellaneousCost { get; set; }
        public decimal? SurchargeCost { get; set; }
        public decimal? VatValue1 { get; set; }
        public decimal? VatValue2 { get; set; }
        public decimal? VatValue3 { get; set; }
        public decimal? VatValue4 { get; set; }
        public DateTime? SalesDueDate { get; set; }
        public DateTime? OriginalDueDate { get; set; }
        public DateTime? DespatchDate { get; set; }
        public DateTime? InvoiceDate { get; set; }
        public decimal? ExchangeRate { get; set; }
        public int? TypeId { get; set; }
        public decimal? BaseMaterialCharge { get; set; }
        public decimal? BaseTransportCharge { get; set; }
        public decimal? BaseProductionCharge { get; set; }
        public decimal? BaseMiscellaneousCharge { get; set; }
        public decimal? BaseSurchargeCharge { get; set; }
        public decimal? BaseMaterialDiscount { get; set; }
        public decimal? BaseTransportDiscount { get; set; }
        public decimal? BaseProductionDiscount { get; set; }
        public decimal? BaseMiscellaneousDiscount { get; set; }
        public decimal? BaseSurchargeDiscount { get; set; }
        public decimal? BaseMaterialValue { get; set; }
        public decimal? BaseTransportValue { get; set; }
        public decimal? BaseProductionValue { get; set; }
        public decimal? BaseMiscellaneousValue { get; set; }
        public decimal? BaseSurchargeValue { get; set; }
        public decimal? BaseVatValue1 { get; set; }
        public decimal? BaseVatValue2 { get; set; }
        public decimal? BaseVatValue3 { get; set; }
        public decimal? BaseVatValue4 { get; set; }
        public int? SalespersonId { get; set; }
        public int? InsideSalespersonId { get; set; }
        public string SpecificationValue1 { get; set; }
        public string SpecificationValue2 { get; set; }
        public string SpecificationValue3 { get; set; }
        public string SpecificationValue4 { get; set; }
        public string SpecificationValue5 { get; set; }
        public int? DeliveryToId { get; set; }
        public int? DeliveryAreaId { get; set; }
        public int? TerritoryId { get; set; }
        public int? OrderBranchId { get; set; }
        public int? DespatchBranchId { get; set; }
        public int? RequestBranchId { get; set; }
        public int? RequestNumber { get; set; }
        public int? RequestItemNumber { get; set; }
        public DateTime? OrderRaisedDate { get; set; }
        public DateTime? DespatchRaisedDate { get; set; }
        public DateTime? InvoicePrintedDate { get; set; }
        public decimal? SalesPrice { get; set; }
        public int? SalesPriceUnitId { get; set; }
        public int? CommodityId { get; set; }
        public string PartNumber { get; set; }
        public string SpecificationValue6 { get; set; }
        public string SpecificationValue7 { get; set; }
        public string SpecificationValue8 { get; set; }
        public string SpecificationValue9 { get; set; }
        public string SpecificationValue10 { get; set; }
        public decimal? StockMaterialCost { get; set; }
        public decimal? StockTransportCost { get; set; }
        public decimal? StockProductionCost { get; set; }
        public decimal? StockMiscellaneousCost { get; set; }
        public decimal? StockSurchargeCost { get; set; }
        public int? InvoiceHeaderId { get; set; }
        public DateTime EtlcreateDate { get; set; }
        public DateTime EtlupdateDate { get; set; }
    }
}
