//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVC.QNG.Exporter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vulcan_CrmQuoteItem_ProductionCost
    {
        public int Id { get; set; }
        public int QIId { get; set; }
        public int QuoteId { get; set; }
        public int QuoteItemId { get; set; }
        public string Coid { get; set; }
        public string LocationName { get; set; }
        public string ResourceType { get; set; }
        public string PerType { get; set; }
        public string TypeName { get; set; }
        public decimal InternalCost { get; set; }
        public decimal ProductionCost { get; set; }
        public decimal MinimumCost { get; set; }
        public decimal TotalPounds { get; set; }
        public decimal TotalInches { get; set; }
        public decimal TotalPieces { get; set; }
        public decimal TotalInternalCost { get; set; }
        public decimal TotalProductionCost { get; set; }
        public Nullable<System.DateTime> ImportDateTimeUTC { get; set; }
        public string BaseCurrency { get; set; }
        public decimal BaseInternalCost { get; set; }
        public decimal BaseMinimumCost { get; set; }
        public decimal BaseProductionCost { get; set; }
        public decimal BaseTotalInternalCost { get; set; }
        public decimal BaseTotalProductionCost { get; set; }
    
        public virtual Vulcan_CrmQuoteItem Vulcan_CrmQuoteItem { get; set; }
    }
}
