//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.HRS.SqlServer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccrualSchedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccrualSchedule()
        {
            this.AccrualDefinition = new HashSet<AccrualDefinition>();
            this.TimeTrackingTimeTrackings_AccrualScheduleAccrualSchedules = new HashSet<TimeTrackingTimeTrackings_AccrualScheduleAccrualSchedules>();
        }
    
        public int OID { get; set; }
        public string Name { get; set; }
        public Nullable<int> LeaveType { get; set; }
        public Nullable<bool> CarryOverFromPreviousYear { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccrualDefinition> AccrualDefinition { get; set; }
        public virtual LeaveType LeaveType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeTrackingTimeTrackings_AccrualScheduleAccrualSchedules> TimeTrackingTimeTrackings_AccrualScheduleAccrualSchedules { get; set; }
    }
}
