//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.HRS.SqlServer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BBS_ObservationItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BBS_ObservationItem()
        {
            this.BBS_ObservationItemObservationItems_BBS_InfluenceOnBehaviorTypeInfluencesOnBehavior = new HashSet<BBS_ObservationItemObservationItems_BBS_InfluenceOnBehaviorTypeInfluencesOnBehavior>();
        }
    
        public int OID { get; set; }
        public Nullable<int> Observation { get; set; }
        public Nullable<int> PrecautionType { get; set; }
        public Nullable<int> SafeCount { get; set; }
        public Nullable<int> ConcernCount { get; set; }
        public string ReasonForConcernWhat { get; set; }
        public string ReasonForConcernWhy { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
        public Nullable<int> InfluenceOnBehavior { get; set; }
        public Nullable<int> InfluenceOnBehaviorType { get; set; }
    
        public virtual BBS_InfluenceOnBehaviorType BBS_InfluenceOnBehaviorType { get; set; }
        public virtual BBS_Observation BBS_Observation { get; set; }
        public virtual BBS_PrecautionType BBS_PrecautionType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BBS_ObservationItemObservationItems_BBS_InfluenceOnBehaviorTypeInfluencesOnBehavior> BBS_ObservationItemObservationItems_BBS_InfluenceOnBehaviorTypeInfluencesOnBehavior { get; set; }
    }
}
