//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.HRS.SqlServer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BenefitPlanType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BenefitPlanType()
        {
            this.BenefitEnrollment = new HashSet<BenefitEnrollment>();
            this.BenefitEnrollmentHistory = new HashSet<BenefitEnrollmentHistory>();
            this.BenefitPlanTypeBenefitPlanTypes_BenefitCoverageTypeBenefitCoverageTypes = new HashSet<BenefitPlanTypeBenefitPlanTypes_BenefitCoverageTypeBenefitCoverageTypes>();
            this.BenefitPlanTypeBenefitPlanTypes_BenefitOptionTypeBenefitOptionTypes = new HashSet<BenefitPlanTypeBenefitPlanTypes_BenefitOptionTypeBenefitOptionTypes>();
        }
    
        public int OID { get; set; }
        public string Name { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BenefitEnrollment> BenefitEnrollment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BenefitEnrollmentHistory> BenefitEnrollmentHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BenefitPlanTypeBenefitPlanTypes_BenefitCoverageTypeBenefitCoverageTypes> BenefitPlanTypeBenefitPlanTypes_BenefitCoverageTypeBenefitCoverageTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BenefitPlanTypeBenefitPlanTypes_BenefitOptionTypeBenefitOptionTypes> BenefitPlanTypeBenefitPlanTypes_BenefitOptionTypeBenefitOptionTypes { get; set; }
    }
}
