//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.HRS.SqlServer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BonusScheme
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BonusScheme()
        {
            this.Compensation2 = new HashSet<Compensation>();
        }
    
        public int OID { get; set; }
        public Nullable<int> Compensation { get; set; }
        public Nullable<int> BonusSchemeType { get; set; }
        public string Comment { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> TargetPercentage { get; set; }
        public Nullable<int> PayFrequency { get; set; }
    
        public virtual BonusSchemeType BonusSchemeType1 { get; set; }
        public virtual Compensation Compensation1 { get; set; }
        public virtual PayFrequencyType PayFrequencyType { get; set; }
        public virtual TargetPercentageType TargetPercentageType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compensation> Compensation2 { get; set; }
    }
}
