//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.HRS.SqlServer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoshhProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CoshhProduct()
        {
            this.CoshhProducts_DisposalMethods = new HashSet<CoshhProducts_DisposalMethods>();
            this.CoshhProducts_FirstAidMeasures = new HashSet<CoshhProducts_FirstAidMeasures>();
            this.CoshhProducts_HazardTypes = new HashSet<CoshhProducts_HazardTypes>();
            this.CoshhProducts_ProductUsageTypes = new HashSet<CoshhProducts_ProductUsageTypes>();
            this.CoshhProducts_RouteOfExposureTypes = new HashSet<CoshhProducts_RouteOfExposureTypes>();
            this.CoshhProducts_StorageMethods = new HashSet<CoshhProducts_StorageMethods>();
            this.CoshhRiskAssessment = new HashSet<CoshhRiskAssessment>();
            this.GhsClassificationGhsClassifications_CoshhProductProducts = new HashSet<GhsClassificationGhsClassifications_CoshhProductProducts>();
        }
    
        public int OID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> ProductType { get; set; }
        public Nullable<int> Manufacturer { get; set; }
        public Nullable<bool> MsdsAvailable { get; set; }
        public string ApplicationMethod { get; set; }
        public string DurationOfExposure { get; set; }
        public string GhsDescription { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
    
        public virtual Manufacturer Manufacturer1 { get; set; }
        public virtual ProductType ProductType1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoshhProducts_DisposalMethods> CoshhProducts_DisposalMethods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoshhProducts_FirstAidMeasures> CoshhProducts_FirstAidMeasures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoshhProducts_HazardTypes> CoshhProducts_HazardTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoshhProducts_ProductUsageTypes> CoshhProducts_ProductUsageTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoshhProducts_RouteOfExposureTypes> CoshhProducts_RouteOfExposureTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoshhProducts_StorageMethods> CoshhProducts_StorageMethods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CoshhRiskAssessment> CoshhRiskAssessment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GhsClassificationGhsClassifications_CoshhProductProducts> GhsClassificationGhsClassifications_CoshhProductProducts { get; set; }
    }
}
