//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.HRS.SqlServer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoshhRiskAssessments_HealthSurveillanceTypes
    {
        public Nullable<int> RiskAssessments { get; set; }
        public Nullable<int> HealthSurveillanceTypes { get; set; }
        public int OID { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
    
        public virtual CoshhRiskAssessment CoshhRiskAssessment { get; set; }
        public virtual HealthSurveillanceType HealthSurveillanceType { get; set; }
    }
}
