//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.HRS.SqlServer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoshhProducts_ProductUsageTypes
    {
        public Nullable<int> Products { get; set; }
        public Nullable<int> ProductUsageTypes { get; set; }
        public int OID { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
    
        public virtual CoshhProduct CoshhProduct { get; set; }
        public virtual ProductUsageType ProductUsageType { get; set; }
    }
}
