//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.HRS.SqlServer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GhsClassification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GhsClassification()
        {
            this.GhsClassificationGhsClassifications_CoshhProductProducts = new HashSet<GhsClassificationGhsClassifications_CoshhProductProducts>();
        }
    
        public int OID { get; set; }
        public Nullable<int> ClassificationType { get; set; }
        public string Comment { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
    
        public virtual GhsClassificationType GhsClassificationType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GhsClassificationGhsClassifications_CoshhProductProducts> GhsClassificationGhsClassifications_CoshhProductProducts { get; set; }
    }
}
