//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.HRS.SqlServer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class kmExport
    {
        public int EOid { get; set; }
        public string FullName { get; set; }
        public int IsUpdateComplete { get; set; }
        public string User_Name { get; set; }
        public string Employee_ID { get; set; }
        public byte[] SSN { get; set; }
        public string Employee_External_ID { get; set; }
        public string EIN_Tax_Id { get; set; }
        public string EIN_NAME { get; set; }
        public string Benefit_Plan { get; set; }
        public string Coverage { get; set; }
        public Nullable<System.DateTime> Coverage_Effective_From { get; set; }
        public Nullable<System.DateTime> Coverage_Effective_TO { get; set; }
        public Nullable<System.DateTime> Effective_From_1 { get; set; }
        public Nullable<System.DateTime> Effective_To_1 { get; set; }
        public Nullable<System.DateTime> Effective_From_2 { get; set; }
        public Nullable<System.DateTime> Effective_To_2 { get; set; }
        public Nullable<System.DateTime> Effective_From_3 { get; set; }
        public Nullable<System.DateTime> Effective_To_3 { get; set; }
        public string Spouse { get; set; }
        public Nullable<System.DateTime> Spouse_Effective_FROM { get; set; }
        public Nullable<System.DateTime> Spouse_Effective_To { get; set; }
        public string Dependent_1 { get; set; }
        public Nullable<System.DateTime> Dependent_1_Effective_From { get; set; }
        public Nullable<System.DateTime> Dependent_1_Effective_TO { get; set; }
        public string Dependent_2 { get; set; }
        public Nullable<System.DateTime> Dependent_2_Effective_FROM { get; set; }
        public Nullable<System.DateTime> Dependent_2_Effective_To { get; set; }
        public string Dependent_3 { get; set; }
        public Nullable<System.DateTime> Dependent_3_Effective_From { get; set; }
        public Nullable<System.DateTime> Dependent_3_Effective_TO { get; set; }
        public string Dependent_4 { get; set; }
        public Nullable<System.DateTime> Dependent_4_Effective_FROM { get; set; }
        public Nullable<System.DateTime> Dependent_4_Effective_To { get; set; }
        public string Dependent_5 { get; set; }
        public Nullable<System.DateTime> Dependent_5_Effective_From { get; set; }
        public Nullable<System.DateTime> Dependent_5_Effective_TO { get; set; }
        public string Dependent_6 { get; set; }
        public Nullable<System.DateTime> Dependent_6_Effective_From { get; set; }
        public Nullable<System.DateTime> Dependent_6_Effective_To { get; set; }
        public string Dependent_7 { get; set; }
        public Nullable<System.DateTime> Dependent_7_Effective_From { get; set; }
        public Nullable<System.DateTime> Dependent_7_Effective_To { get; set; }
        public string Beneficiary_1 { get; set; }
        public Nullable<decimal> Beneficiary_1_Percent { get; set; }
        public Nullable<System.DateTime> Beneficiary_1_Effective_FROM { get; set; }
        public Nullable<System.DateTime> Beneficiary_1_Effective_To { get; set; }
        public string Contingent_Beneficiary_1 { get; set; }
        public Nullable<decimal> Contingent_Beneficiary_1_Percent { get; set; }
        public Nullable<System.DateTime> Contingent_Beneficiary_1_Effective_FROM { get; set; }
        public Nullable<System.DateTime> Contingent_Beneficiary_1_Effective_TO { get; set; }
        public string Contingent_Beneficiary_2 { get; set; }
        public Nullable<decimal> Contingent_Beneficiary_2_Percent { get; set; }
        public Nullable<System.DateTime> Contingent_Beneficiary_2_Effective_FROM { get; set; }
        public Nullable<System.DateTime> Contingent_Beneficiary_2_Effective_To { get; set; }
        public Nullable<decimal> Benefit_Salary_1 { get; set; }
        public Nullable<System.DateTime> Benefit_Salary_1_Effective_FROM { get; set; }
        public Nullable<decimal> Benefit_Salary_2 { get; set; }
        public Nullable<System.DateTime> Benefit_Salary_2_Effective_From { get; set; }
        public Nullable<decimal> Benefit_Salary_3 { get; set; }
        public Nullable<System.DateTime> Benefit_Salary_3_Effective_From { get; set; }
        public Nullable<decimal> Benefit_Salary_4 { get; set; }
        public Nullable<System.DateTime> Benefit_Salary_4_Effective_From { get; set; }
        public Nullable<decimal> Benefit_Salary_5 { get; set; }
        public Nullable<System.DateTime> Benefit_Salary_5_Effective_From { get; set; }
        public int Units { get; set; }
        public Nullable<System.DateTime> Adjust_End_Date { get; set; }
        public string Location { get; set; }
        public string CountryName { get; set; }
        public string CountryOfOrigin { get; set; }
    }
}
