//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.HRS.SqlServer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedLeave
    {
        public int OID { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
        public Nullable<int> MedicalInfo { get; set; }
        public Nullable<int> LeaveType { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<int> DaysAway { get; set; }
        public string Notes { get; set; }
    
        public virtual MedicalInfo MedicalInfo1 { get; set; }
        public virtual MedicalLeaveType MedicalLeaveType { get; set; }
    }
}
