//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.HRS.SqlServer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PremiumCompensation
    {
        public int OID { get; set; }
        public Nullable<int> Compensation { get; set; }
        public Nullable<int> PremiumCompensationType { get; set; }
        public Nullable<int> PremiumCompensationValueType { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
        public byte[] Comment { get; set; }
    
        public virtual Compensation Compensation1 { get; set; }
        public virtual PremiumCompensationType PremiumCompensationType1 { get; set; }
        public virtual PremiumCompensationValueType PremiumCompensationValueType1 { get; set; }
    }
}
