//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.HRS.SqlServer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatingOutcome
    {
        public int OID { get; set; }
        public Nullable<int> Performance { get; set; }
        public Nullable<int> PerformanceHistory { get; set; }
        public Nullable<int> RatingOutcomeType { get; set; }
        public string Comment { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
    
        public virtual Performance Performance1 { get; set; }
        public virtual PerformanceHistory PerformanceHistory1 { get; set; }
        public virtual RatingOutcomeType RatingOutcomeType1 { get; set; }
    }
}
