//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.HRS.SqlServer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTracking2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TimeTracking2()
        {
            this.TimeTracking2SupportingDocument = new HashSet<TimeTracking2SupportingDocument>();
            this.TimeTracking2TimeTrackings_AccrualPolicyAccrualPolicies = new HashSet<TimeTracking2TimeTrackings_AccrualPolicyAccrualPolicies>();
        }
    
        public int OID { get; set; }
        public Nullable<int> Employee { get; set; }
        public Nullable<int> AccrualProfile { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
    
        public virtual AccrualProfile AccrualProfile1 { get; set; }
        public virtual Employee Employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeTracking2SupportingDocument> TimeTracking2SupportingDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeTracking2TimeTrackings_AccrualPolicyAccrualPolicies> TimeTracking2TimeTrackings_AccrualPolicyAccrualPolicies { get; set; }
    }
}
