//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.HRS.SqlServer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingCourse_Locations
    {
        public Nullable<int> Locations { get; set; }
        public Nullable<int> TrainingCourses { get; set; }
        public int OID { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
    
        public virtual TrainingCourse TrainingCourse { get; set; }
        public virtual Location Location { get; set; }
    }
}
