//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.HRS.SqlServer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Training
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Training()
        {
            this.TrainingAttendee = new HashSet<TrainingAttendee>();
            this.TrainingEventSupportingDocument = new HashSet<TrainingEventSupportingDocument>();
        }
    
        public int OID { get; set; }
        public Nullable<int> CourseType { get; set; }
        public Nullable<int> Location { get; set; }
        public Nullable<int> Course { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> CertificateExpiration { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<int> OptimisticLockField { get; set; }
        public Nullable<int> GCRecord { get; set; }
        public Nullable<int> TrainingHours { get; set; }
        public Nullable<int> CourseVenueType { get; set; }
        public string ExternalInstructor { get; set; }
        public Nullable<int> InternalInstructor { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual TrainingCourse TrainingCourse { get; set; }
        public virtual TrainingCourseType TrainingCourseType { get; set; }
        public virtual TrainingCourseVenueType TrainingCourseVenueType { get; set; }
        public virtual Location Location1 { get; set; }
        public virtual TrainingHoursType TrainingHoursType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingAttendee> TrainingAttendee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingEventSupportingDocument> TrainingEventSupportingDocument { get; set; }
    }
}
