//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.HRS.SqlServer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebPortal_EmailRecipients
    {
        public int ID { get; set; }
        public string DisplayName { get; set; }
        public string TestEmail { get; set; }
        public string ProdEmail { get; set; }
        public string GroupKey { get; set; }
        public string Region { get; set; }
    }
}
